title: ROM ROBOTICS
description: Open Source Robotics Community from Myanmar
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

github:
  home_url: https://romrobots.com
  github_url: https://github.com/ROM-robotics
  user_url: https://userguide.romrobots.com
  developer_url: https://developer.romrobots.com
  contact_url: https://contactus.romrobots.com
